/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MVC.View;

import MVC.Controller.ControllerAppoint;
import MVC.Controller.ControllerBilling;
import MVC.Controller.ControllerMedications;
import MVC.Controller.ControllerOwner;
import MVC.Controller.ControllerSuppliers;
import MVC.Controller.ControllerSupplies;
import MVC.Controller.ControllerUser;
import MVC.Controller.ctrlLogin;
import MVC.Model.AppointDAO;
import MVC.Model.BillingDAO;
import MVC.Model.Login;
import MVC.Model.LoginDAO;
import MVC.Model.MedicationsDAO;
import MVC.Model.OwnerDAO;
import MVC.Model.PetsDAO;
import MVC.Model.SupplierDAO;
import MVC.Model.SuppliesDAO;
import MVC.Model.User;
import MVC.Model.UserDAO;
import MVC.Model.billing;
import MVC.Model.medical_consultations;
import MVC.Model.medications;
import MVC.Model.pets;
import MVC.Model.suppliers;
import MVC.Model.supplies;
import MVC.controller.petsController;

/**
 *
 * @author const
 */
public class MenuAdmi extends javax.swing.JFrame {

    /**
     * Creates new form MenuAdmi
     */
    public MenuAdmi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbMenu = new javax.swing.JLabel();
        lbAdmi = new javax.swing.JLabel();
        btManageUser = new javax.swing.JButton();
        btManageOwner = new javax.swing.JButton();
        btManagePet = new javax.swing.JButton();
        btManageAppoint = new javax.swing.JButton();
        btLogout = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        bntMnageMedication = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(96, 163, 188));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(100, 500));

        lbMenu.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        lbMenu.setForeground(new java.awt.Color(255, 255, 255));
        lbMenu.setText("WELCOME");

        lbAdmi.setFont(new java.awt.Font("Segoe Script", 1, 30)); // NOI18N
        lbAdmi.setForeground(new java.awt.Color(255, 255, 255));
        lbAdmi.setText("Administration");

        btManageUser.setBackground(new java.awt.Color(255, 255, 255));
        btManageUser.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        btManageUser.setForeground(new java.awt.Color(44, 62, 80));
        btManageUser.setText("Manage Users");
        btManageUser.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btManageUser.setPreferredSize(new java.awt.Dimension(157, 32));
        btManageUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btManageUserActionPerformed(evt);
            }
        });

        btManageOwner.setBackground(new java.awt.Color(255, 255, 255));
        btManageOwner.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        btManageOwner.setForeground(new java.awt.Color(44, 62, 80));
        btManageOwner.setText("Manage Owner");
        btManageOwner.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btManageOwner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btManageOwnerActionPerformed(evt);
            }
        });

        btManagePet.setBackground(new java.awt.Color(255, 255, 255));
        btManagePet.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        btManagePet.setForeground(new java.awt.Color(44, 62, 80));
        btManagePet.setText("Manage Pets");
        btManagePet.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btManagePet.setPreferredSize(new java.awt.Dimension(157, 32));
        btManagePet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btManagePetActionPerformed(evt);
            }
        });

        btManageAppoint.setBackground(new java.awt.Color(255, 255, 255));
        btManageAppoint.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        btManageAppoint.setForeground(new java.awt.Color(44, 62, 80));
        btManageAppoint.setText("Manage Appointments");
        btManageAppoint.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btManageAppoint.setPreferredSize(new java.awt.Dimension(157, 32));
        btManageAppoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btManageAppointActionPerformed(evt);
            }
        });

        btLogout.setBackground(new java.awt.Color(44, 62, 80));
        btLogout.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btLogout.setForeground(new java.awt.Color(255, 255, 255));
        btLogout.setText("Log out");
        btLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLogoutActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        jButton1.setForeground(new java.awt.Color(44, 62, 80));
        jButton1.setText("Manage Suppliers");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.setPreferredSize(new java.awt.Dimension(157, 32));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        bntMnageMedication.setBackground(new java.awt.Color(255, 255, 255));
        bntMnageMedication.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        bntMnageMedication.setForeground(new java.awt.Color(44, 62, 80));
        bntMnageMedication.setText("Manage Medications");
        bntMnageMedication.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bntMnageMedication.setPreferredSize(new java.awt.Dimension(157, 32));
        bntMnageMedication.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntMnageMedicationActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        jButton3.setForeground(new java.awt.Color(44, 62, 80));
        jButton3.setText("Manage Supplies");
        jButton3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3.setPreferredSize(new java.awt.Dimension(157, 32));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        jButton5.setForeground(new java.awt.Color(44, 62, 80));
        jButton5.setText("Manage Billing");
        jButton5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton5.setPreferredSize(new java.awt.Dimension(157, 32));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lbAdmi)
                        .addGap(89, 89, 89))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lbMenu)
                        .addGap(131, 131, 131))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btManageAppoint, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btManageUser, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(51, 51, 51)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btManagePet, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btManageOwner, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bntMnageMedication, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(btLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbMenu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbAdmi)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btManageOwner, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btManageUser, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btManagePet, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btManageAppoint, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bntMnageMedication, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(btLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLogoutActionPerformed
        Login log = new Login();
        LoginView lv = new LoginView();
        LoginDAO dao = new LoginDAO();
        ctrlLogin ctrlL = new ctrlLogin(log, dao, lv);
        lv.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btLogoutActionPerformed

    private void btManageAppointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btManageAppointActionPerformed
        crudAppoint ca = new crudAppoint();
        AppointDAO dao = new AppointDAO();
        medical_consultations mc = new medical_consultations();
        ControllerAppoint ctrlA = new ControllerAppoint(mc, dao, ca);
        ca.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btManageAppointActionPerformed

    private void btManagePetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btManagePetActionPerformed
        Vista v = new Vista();
        PetsDAO dao = new PetsDAO();
        pets pet = new pets();
        petsController ctrlP = new petsController(v, dao, pet);
        v.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btManagePetActionPerformed

    private void bntMnageMedicationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntMnageMedicationActionPerformed
        crudMedications cm = new crudMedications();
        medications medi = new medications();
        MedicationsDAO dao = new MedicationsDAO();
        ControllerMedications ctrlM = new ControllerMedications(medi, dao, cm);
        cm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bntMnageMedicationActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        crudBillings cb = new crudBillings();
        billing bi = new billing();
        BillingDAO dao = new BillingDAO();
        ControllerBilling ctrlB = new ControllerBilling(dao, bi, cb);
        cb.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btManageOwnerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btManageOwnerActionPerformed
        crudOwner co = new crudOwner();
        OwnerDAO dao = new OwnerDAO();
        User user = new User();
        ControllerOwner ctrlO = new ControllerOwner(dao, user, co);
        co.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_btManageOwnerActionPerformed

    private void btManageUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btManageUserActionPerformed
        crudUsers cu = new crudUsers();
        UserDAO dao = new UserDAO();
        User user = new User();
        ControllerUser ctrlU = new ControllerUser(dao, user, cu);
        cu.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_btManageUserActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        crudSuppliers cs = new crudSuppliers();
        SupplierDAO dao = new SupplierDAO();
        suppliers su = new suppliers();
        ControllerSuppliers ctrlSp = new ControllerSuppliers(dao, su, cs);
        cs.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        crudSupplies cs = new crudSupplies();
        SuppliesDAO dao = new SuppliesDAO();
        supplies sup = new supplies();
        ControllerSupplies ctrlSup = new ControllerSupplies(dao, sup, cs);
        cs.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuAdmi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuAdmi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuAdmi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuAdmi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuAdmi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton bntMnageMedication;
    public javax.swing.JButton btLogout;
    public javax.swing.JButton btManageAppoint;
    public javax.swing.JButton btManageOwner;
    public javax.swing.JButton btManagePet;
    public javax.swing.JButton btManageUser;
    public javax.swing.JButton jButton1;
    public javax.swing.JButton jButton3;
    public javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JLabel lbAdmi;
    public javax.swing.JLabel lbMenu;
    // End of variables declaration//GEN-END:variables
}
